# file: C:\Users\ADITI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\numpy\exceptions.py
# hypothesis_version: 6.135.14

['AxisError', 'ComplexWarning', 'DTypePromotionError', 'TooHardError', '_is_loaded', '_msg', 'axis', 'ndim']