# file: C:\Users\ADITI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\attr\exceptions.py
# hypothesis_version: 6.135.14

["can't set attribute"]